

#include <linux/ioctl.h>

#define XR21B1411_IOC_MAGIC       	'v'

#define XRUSBIOC_GET_REG           	_IOWR(XR21B1411_IOC_MAGIC, 1, int)
#define XRUSBIOC_SET_REG           	_IOWR(XR21B1411_IOC_MAGIC, 2, int)
#define XRUSBIOC_SET_ADDRESS_MATCH  	_IO(XR21B1411_IOC_MAGIC, 3)
#define XRUSBIOC_SET_PRECISE_FLAGS  	_IO(XR21B1411_IOC_MAGIC, 4)
#define XRUSBIOC_TEST_MODE         	_IO(XR21B1411_IOC_MAGIC, 5)
#define XRUSBIOC_LOOPBACK          	_IO(XR21B1411_IOC_MAGIC, 6)

#define XRUSB_ADDRESS_UNICAST_S     0 
#define XRUSB_ADDRESS_BROADCAST_S   8 
#define XRUSB_ADDRESS_MATCH(U, B)   (0x8000000 | ((B) << XRUSB_ADDRESS_BROADCAST_S) | ((U) << XRUSB_ADDRESS_UNICAST_S)) 
#define XRUSB_ADDRESS_MATCH_DISABLE 0 
